rootProject.name = "printscript"
include("lexer")
include("syntax")
include("models")
include("semantics")
include("interpreter")
include("formatter")
include("cli")
include("testframework")
include("staticanalyzer")
