#!/bin/sh
separator="====================="

set -e
echo $separator
echo "Applying Spotless"
./gradlew spotlessApply
echo $separator

#Once applied spotless, move to checkStyle

echo $separator
echo "Using CheckStyle"
./gradlew checkstyleMain
./gradlew checkstyleTest
echo $separator

echo $separator
echo "SUCCESSFUL COMMIT"
echo $separator

