@startuml

interface SemanticAnalyzer {
    + analyze(List<AstComponent> tokens): SemanticResult
}

class InOrderAnalyzer implements SemanticAnalyzer {
    + analyze(List<AstComponent> tokens): SemanticResult
}

interface SemanticResult

class SemanticSuccess implements SemanticResult
class SemanticFailure implements SemanticResult {
    - reason: String
}

interface Resolver {
    + resolve(Ast ast, Set<Declaration> previousDeclarations): Resolution
}

class Resolution {
    - result: SemanticResult
    - resolvedType: Class<T extends AstComponent>
    - resolvedDeclarations: Set<Declaration>
}

SemanticAnalyzer -> SemanticResult
InOrderAnalyzer --> Resolver
Resolver -> Resolution

@enduml