package org.example.ruleappliers.ifelse;

import org.example.ruleappliers.ApplicableSpaces;

public enum IfElseSpaces implements ApplicableSpaces {
	SPACES_BEFORE_IF,
	SPACES_AFTER_IF,
	SPACES_BEFORE_CONDITION,
	SPACES_AFTER_CONDITION,
	SPACES_BEFORE_IF_BLOCK,
	SPACES_IN_IF_BLOCK_START,
	INDENTATION_IN_IF_BLOCK,
	SPACES_IN_IF_BLOCK_END,
	SPACES_AFTER_IF_BLOCK,
	SPACES_BEFORE_ELSE_BLOCK,
	SPACES_IN_ELSE_BLOCK_START,
	INDENTATION_ELSE_IN_BLOCK,
	SPACES_IN_ELSE_BLOCK_END,
	SPACES_AFTER_ELSE_BLOCK
}
